// This script runs before your site is built
// It creates the config files using environment variables

const fs = require('fs');
require('dotenv').config(); // Load variables from .env file

// === Create Gemini Config ===
const geminiConfigContent = `
// This file is generated by create-config.js. DO NOT EDIT.

const GEMINI_API_KEY = '${process.env.GEMINI_API_KEY}';
const GEMINI_API_URL = 'https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent';

// Model configurations for different content types
export const GEMINI_MODELS = {
    quest: 'gemini-1.5-flash',
    quiz: 'gemini-1.5-flash',
    content: 'gemini-1.5-pro'
};

// Safety settings for educational content
export const SAFETY_SETTINGS = [
    {
        category: "HARM_CATEGORY_HARASSMENT",
        threshold: "BLOCK_MEDIUM_AND_ABOVE"
    },
    {
        category: "HARM_CATEGORY_HATE_SPEECH", 
        threshold: "BLOCK_MEDIUM_AND_ABOVE"
    },
    {
        category: "HARM_CATEGORY_SEXUALLY_EXPLICIT",
        threshold: "BLOCK_MEDIUM_AND_ABOVE"
    },
    {
        category: "HARM_CATEGORY_DANGEROUS_CONTENT",
        threshold: "BLOCK_MEDIUM_AND_ABOVE"
    }
];

// Generation parameters
export const GENERATION_CONFIG = {
    temperature: 0.7,
    topK: 40,
    topP: 0.95,
    maxOutputTokens: 2048,
};

// API client configuration
export const GEMINI_CONFIG = {
    apiKey: GEMINI_API_KEY,
    apiUrl: GEMINI_API_URL,
    safetySettings: SAFETY_SETTINGS,
    generationConfig: GENERATION_CONFIG
};
`;

// === Create Firebase Config ===
const firebaseConfigContent = `
// This file is generated by create-config.js. DO NOT EDIT.

import { initializeApp } from "https://www.gstatic.com/firebasejs/10.12.0/firebase-app.js";
import { getAuth } from "https://www.gstatic.com/firebasejs/10.12.0/firebase-auth.js";
import { getFirestore } from "https://www.gstatic.com/firebasejs/10.12.0/firebase-firestore.js";
import { getStorage } from "https://www.gstatic.com/firebasejs/10.12.0/firebase-storage.js";

const firebaseConfig = {
  apiKey: "${process.env.FIREBASE_API_KEY}",
  authDomain: "${process.env.FIREBASE_AUTH_DOMAIN}",
  projectId: "${process.env.FIREBASE_PROJECT_ID}",
  storageBucket: "${process.env.FIREBASE_STORAGE_BUCKET}",
  messagingSenderId: "${process.env.FIREBASE_MESSAGING_SENDER_ID}",
  appId: "${process.env.FIREBASE_APP_ID}",
  measurementId: "${process.env.FIREBASE_MEASUREMENT_ID}"
};

const app = initializeApp(firebaseConfig);
export const auth = getAuth(app);
export const db = getFirestore(app);
export const storage = getStorage(app);
export default app;
`;

// Write the files
// Ensure the directory exists before writing
const configDir = 'js/config';
if (!fs.existsSync(configDir)){
    fs.mkdirSync(configDir, { recursive: true });
}

fs.writeFileSync('js/config/gemini-config.js', geminiConfigContent.trim());
fs.writeFileSync('js/config/firebase-config.js', firebaseConfigContent.trim());

console.log('Successfully created config files.');

