// This file is generated by create-config.js. DO NOT EDIT.

import { initializeApp } from "https://www.gstatic.com/firebasejs/10.12.0/firebase-app.js";
import { getAuth } from "https://www.gstatic.com/firebasejs/10.12.0/firebase-auth.js";
import { getFirestore } from "https://www.gstatic.com/firebasejs/10.12.0/firebase-firestore.js";
import { getStorage } from "https://www.gstatic.com/firebasejs/10.12.0/firebase-storage.js";

const firebaseConfig = {
  apiKey: "AIzaSyDKORSxuutBkLR98kvYNE5jJa0TlGFGSqo",
  authDomain: "ecoquest-115da.firebaseapp.com",
  projectId: "ecoquest-115da",
  storageBucket: "ecoquest-115da.firebasestorage.app",
  messagingSenderId: "862557922154",
  appId: "1:862557922154:web:cef96c9c9d519a41f6fb13",
  measurementId: "G-V9XG0NM37J"
};

const app = initializeApp(firebaseConfig);
export const auth = getAuth(app);
export const db = getFirestore(app);
export const storage = getStorage(app);
export default app;