import { GEMINI_CONFIG, GEMINI_MODELS, SAFETY_SETTINGS, GENERATION_CONFIG } from '../config/gemini-config.js';
import { createQuestPrompt, createQuizPrompt, createMissionPrompt } from './prompt-templates.js';

// Gemini API client for content generation
export class GeminiClient {
    constructor() {
        this.apiKey = GEMINI_CONFIG.apiKey;
        // ✅ UPDATED: Use the base URL that works with current models
        this.apiUrl = 'https://generativelanguage.googleapis.com/v1beta/models';
    }
    
    // ✅ UPDATED: Get the correct API endpoint for each model
    getModelEndpoint(model = 'gemini-2.0-flash') {
        // Map old model names to new ones
        const modelMapping = {
            'gemini-1.5-flash': 'gemini-2.0-flash',
            'gemini-1.5-pro': 'gemini-2.5-pro',
            'gemini-pro': 'gemini-2.0-flash',
            'gemini-flash': 'gemini-2.0-flash'
        };
        
        const actualModel = modelMapping[model] || model;
        return `${this.apiUrl}/${actualModel}:generateContent`;
    }
    
    // Generate content using Gemini API
    async generateContent(prompt, model = 'gemini-2.0-flash') {
        try {
            const requestBody = {
                contents: [{
                    parts: [{ text: prompt }]
                }],
                safetySettings: SAFETY_SETTINGS,
                generationConfig: GENERATION_CONFIG
            };
            
            console.log('Sending request to Gemini API...');
            console.log('Using model:', model);
            
            // ✅ UPDATED: Use the new endpoint method
            const endpoint = this.getModelEndpoint(model);
            console.log('API Endpoint:', endpoint);
            
            const response = await fetch(`${endpoint}?key=${this.apiKey}`, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify(requestBody)
            });
            
            if (!response.ok) {
                const errorData = await response.json().catch(() => null);
                console.error('Gemini API Error Response:', errorData);
                
                // ✅ IMPROVED: Better error handling for common issues
                if (response.status === 404) {
                    throw new Error(`Model "${model}" not found. Please check if the model name is correct and supported.`);
                } else if (response.status === 403) {
                    throw new Error('Gemini API access denied. Please check your API key and permissions.');
                } else if (response.status === 429) {
                    throw new Error('Gemini API rate limit exceeded. Please try again later.');
                }
                
                throw new Error(`Gemini API error: ${response.status} - ${errorData?.error?.message || response.statusText}`);
            }
            
            const data = await response.json();
            console.log('Raw Gemini API response:', data);
            
            if (!data.candidates || data.candidates.length === 0) {
                console.error('No candidates in response:', data);
                throw new Error('No content generated by Gemini API');
            }
            
            const candidate = data.candidates[0];
            if (!candidate.content || !candidate.content.parts || candidate.content.parts.length === 0) {
                console.error('Invalid candidate structure:', candidate);
                throw new Error('Invalid response structure from Gemini API');
            }
            
            const generatedText = candidate.content.parts[0].text;
            console.log('Generated text from Gemini:', generatedText);
            
            return this.parseResponse(generatedText);
            
        } catch (error) {
            console.error('Error in generateContent:', error);
            
            // ✅ IMPROVED: More specific error messages
            if (error.message.includes('API key')) {
                throw new Error('Invalid or missing Gemini API key. Please check your configuration.');
            } else if (error.message.includes('quota') || error.message.includes('limit')) {
                throw new Error('Gemini API quota exceeded. Please try again later or check your billing.');
            } else if (error.message.includes('safety')) {
                throw new Error('Content was blocked by safety filters. Try rephrasing your prompt.');
            } else if (error.message.includes('not found') || error.message.includes('404')) {
                throw new Error('Gemini model not available. The API has been updated to use newer model names.');
            }
            
            throw error;
        }
    }
    
    // Parse JSON response from Gemini
    parseResponse(text) {
        try {
            let cleanText = text.trim();
            
            // Remove markdown code blocks if present (FIXED - proper regex)
            cleanText = cleanText.replace(/^```(?:json)?\s*/g, '');
            cleanText = cleanText.replace(/\n?```\s*$/g, '');
            cleanText = cleanText.trim();
            
            console.log('Cleaned text for parsing:', cleanText);
            
            const parsed = JSON.parse(cleanText);
            
            if (!parsed) {
                throw new Error('Empty response from Gemini API');
            }
            
            return parsed;
            
        } catch (error) {
            console.error('Error parsing Gemini response:', error);
            console.log('Raw response text:', text);
            console.log('Cleaned text attempt:', text.trim().replace(/^```(?:json)?\s*/g, '').replace(/\n?```\s*$/g, '').trim());
            
            if (text.indexOf('```') !== -1) {
                console.warn('Response contains markdown formatting - this may cause parsing issues');
            }
            
            if (text.indexOf('{') !== -1 || text.indexOf('[') !== -1) {
                console.warn('Response appears to contain JSON but parsing failed');
            }
            
            throw new Error('Failed to parse AI response: ' + error.message);
        }
    }
    
    // ✅ FIXED: Generate quest content with new models
async generateQuest(params) {
    try {
        const prompt = createQuestPrompt(params);
        // Use the newer, faster model for quest generation
        const response = await this.generateContent(prompt, 'gemini-2.0-flash');
        
        if (!response.quests || !Array.isArray(response.quests) || response.quests.length === 0) {
            throw new Error('No quests found in AI response');
        }
        
        // ✅ FIX: Return the first quest from the array, not the entire array
        return response.quests[0];
    } catch (error) {
        console.error('Error generating quest:', error);
        throw error;
    }
}
    
    // ✅ UPDATED: Generate multiple quests with optimized model
    async generateQuests(params) {
        try {
            const questParams = { ...params, questCount: params.count || 3 };
            const prompt = createQuestPrompt(questParams);
            // Use the more capable model for multiple quests
            const response = await this.generateContent(prompt, 'gemini-2.5-flash');
            
            if (!response.quests || !Array.isArray(response.quests)) {
                throw new Error('Invalid quests array in AI response');
            }
            
            return response.quests;
        } catch (error) {
            console.error('Error generating quests:', error);
            throw error;
        }
    }
    
    // ✅ UPDATED: Generate quiz questions with appropriate model
    async generateQuiz(params) {
        try {
            const prompt = createQuizPrompt(params);
            const response = await this.generateContent(prompt, 'gemini-2.0-flash');
            
            if (!response.questions || !Array.isArray(response.questions)) {
                throw new Error('Invalid questions array in AI response');
            }
            
            return response.questions;
        } catch (error) {
            console.error('Error generating quiz:', error);
            throw error;
        }
    }
    
    // ✅ UPDATED: Generate single mission with latest model
    async generateMission(params) {
        try {
            const prompt = createMissionPrompt(params);
            const response = await this.generateContent(prompt, 'gemini-2.0-flash');
            
            if (!response.mission) {
                throw new Error('No mission found in AI response');
            }
            
            return response.mission;
        } catch (error) {
            console.error('Error generating mission:', error);
            throw error;
        }
    }
    
    // Batch generate content for multiple regions
    async generateRegionalContent(baseParams, states) {
        const results = {};
        
        for (const state of states) {
            try {
                console.log('Generating content for ' + state + '...');
                const stateParams = { ...baseParams, userState: state };
                const quests = await this.generateQuests(stateParams);
                results[state] = { success: true, quests };
                
                // ✅ IMPROVED: Slightly longer delay to respect rate limits
                await new Promise(resolve => setTimeout(resolve, 3000));
            } catch (error) {
                console.error('Error generating content for ' + state + ':', error);
                results[state] = { success: false, error: error.message };
            }
        }
        
        return results;
    }
    
    // ✅ UPDATED: Test API connection with current model
    async testConnection() {
        try {
            const testPrompt = 'Generate a simple JSON response: {"message": "API connection successful", "timestamp": "' + new Date().toISOString() + '", "model": "gemini-2.0-flash"}';
            const response = await this.generateContent(testPrompt, 'gemini-2.0-flash');
            return { success: true, response };
        } catch (error) {
            return { success: false, error: error.message };
        }
    }
    
    // Validate API key
    validateApiKey() {
        if (!this.apiKey || this.apiKey === 'YOUR_GEMINI_API_KEY_HERE') {
            throw new Error('Please set your Gemini API key in gemini-config.js');
        }
        return true;
    }
    
    // ✅ UPDATED: Get API usage info with current models
    async getApiInfo() {
        try {
            this.validateApiKey();
            return {
                apiKey: this.apiKey.substring(0, 10) + '...',
                baseUrl: this.apiUrl,
                supportedModels: [
                    'gemini-2.0-flash',
                    'gemini-2.5-flash', 
                    'gemini-2.5-pro'
                ],
                configured: true
            };
        } catch (error) {
            return {
                configured: false,
                error: error.message
            };
        }
    }
    
    // ✅ NEW: Get available models (for debugging)
    getSupportedModels() {
        return [
            {
                name: 'gemini-2.0-flash',
                description: 'Latest fast model, best for quick generation',
                recommended: true
            },
            {
                name: 'gemini-2.5-flash', 
                description: 'Stable fast model, good for multiple content',
                recommended: false
            },
            {
                name: 'gemini-2.5-pro',
                description: 'Most capable model, slower but higher quality',
                recommended: false
            }
        ];
    }
}

// Create global instance
export const geminiClient = new GeminiClient();

// Helper function to validate generated content
export function validateGeneratedQuest(quest) {
    const required = ['id', 'title', 'description', 'category', 'difficulty', 'missions'];
    const missing = required.filter(field => !quest[field]);
    
    if (missing.length > 0) {
        throw new Error('Generated quest missing required fields: ' + missing.join(', '));
    }
    
    if (!Array.isArray(quest.missions) || quest.missions.length === 0) {
        throw new Error('Quest must have at least one mission');
    }
    
    quest.missions.forEach((mission, index) => {
        const missionRequired = ['id', 'title', 'description', 'type', 'xpReward', 'content'];
        const missionMissing = missionRequired.filter(field => !mission[field]);
        
        if (missionMissing.length > 0) {
            throw new Error('Mission ' + (index + 1) + ' missing required fields: ' + missionMissing.join(', '));
        }
    });
    
    return true;
}

// Helper function to sanitize AI-generated content
export function sanitizeGeneratedContent(content) {
    if (typeof content === 'string') {
        return content
            .replace(/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi, '')
            .replace(/javascript:/gi, '')
            .replace(/on\w+\s*=/gi, '')
            .trim();
    }
    
    if (typeof content === 'object' && content !== null) {
        const sanitized = {};
        for (const [key, value] of Object.entries(content)) {
            sanitized[key] = sanitizeGeneratedContent(value);
        }
        return sanitized;
    }
    
    return content;
}

// ✅ UPDATED: Test function with current models
export async function testGeminiConnection() {
    try {
        console.log('Testing Gemini API connection...');
        
        const client = new GeminiClient();
        const apiInfo = await client.getApiInfo();
        console.log('API Info:', apiInfo);
        
        if (!apiInfo.configured) {
            throw new Error(apiInfo.error);
        }
        
        console.log('Supported models:', client.getSupportedModels());
        
        const testResult = await client.testConnection();
        console.log('Connection test result:', testResult);
        
        return testResult;
    } catch (error) {
        console.error('Gemini connection test failed:', error);
        return { success: false, error: error.message };
    }
}