import { GEMINI_CONFIG, GEMINI_MODELS, SAFETY_SETTINGS, GENERATION_CONFIG } from '../config/gemini-config.js';
import { createQuestPrompt, createQuizPrompt, createMissionPrompt } from './prompt-templates.js';

// Gemini API client for content generation
export class GeminiClient {
    constructor() {
        this.apiKey = GEMINI_CONFIG.apiKey;
        this.apiUrl = GEMINI_CONFIG.apiUrl;
    }
    
    // Generate content using Gemini API
    async generateContent(prompt, model = 'gemini-1.5-flash') {
        try {
            const requestBody = {
                contents: [{
                    parts: [{ text: prompt }]
                }],
                safetySettings: SAFETY_SETTINGS,
                generationConfig: GENERATION_CONFIG
            };
            
            console.log('Sending request to Gemini API...');
            
            const response = await fetch(this.apiUrl + '?key=' + this.apiKey, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify(requestBody)
            });
            
            if (!response.ok) {
                const errorText = await response.text();
                console.error('Gemini API Error Response:', errorText);
                throw new Error('Gemini API error: ' + response.status + ' ' + response.statusText);
            }
            
            const data = await response.json();
            console.log('Raw Gemini API response:', data);
            
            if (!data.candidates || data.candidates.length === 0) {
                console.error('No candidates in response:', data);
                throw new Error('No content generated by Gemini API');
            }
            
            const candidate = data.candidates[0];
            if (!candidate.content || !candidate.content.parts || candidate.content.parts.length === 0) {
                console.error('Invalid candidate structure:', candidate);
                throw new Error('Invalid response structure from Gemini API');
            }
            
            const generatedText = candidate.content.parts[0].text;
            console.log('Generated text from Gemini:', generatedText);
            
            return this.parseResponse(generatedText);
            
        } catch (error) {
            console.error('Error in generateContent:', error);
            
            if (error.message.includes('API key')) {
                throw new Error('Invalid or missing Gemini API key. Please check your configuration.');
            } else if (error.message.includes('quota')) {
                throw new Error('Gemini API quota exceeded. Please try again later.');
            } else if (error.message.includes('safety')) {
                throw new Error('Content was blocked by safety filters. Try rephrasing your prompt.');
            }
            
            throw error;
        }
    }
    
    // Parse JSON response from Gemini
    parseResponse(text) {
        try {
            let cleanText = text.trim();
            
            // Remove markdown code blocks if present (FIXED - proper regex)
            cleanText = cleanText.replace(/^```[a-z]*\n?/gi, '');
            cleanText = cleanText.replace(/\n?```\s*$/g, '');
            cleanText = cleanText.trim();
            
            console.log('Cleaned text for parsing:', cleanText);
            
            const parsed = JSON.parse(cleanText);
            
            if (!parsed) {
                throw new Error('Empty response from Gemini API');
            }
            
            return parsed;
            
        } catch (error) {
            console.error('Error parsing Gemini response:', error);
            console.log('Raw response text:', text);
            console.log('Cleaned text attempt:', text.trim().replace(/^```[a-z]*\n?/gi, '').replace(/\n?```\s*$/g, '').trim());
            
            if (text.indexOf('```') !== -1) {
                console.warn('Response contains markdown formatting - this may cause parsing issues');
            }
            
            if (text.indexOf('{') !== -1 || text.indexOf('[') !== -1) {
                console.warn('Response appears to contain JSON but parsing failed');
            }
            
            throw new Error('Failed to parse AI response: ' + error.message);
        }
    }
    
    // Generate quest content
    async generateQuest(params) {
        try {
            const prompt = createQuestPrompt(params);
            const response = await this.generateContent(prompt, GEMINI_MODELS.quest);
            
            if (!response.quests || !Array.isArray(response.quests) || response.quests.length === 0) {
                throw new Error('No quests found in AI response');
            }
            
            return response.quests[0];
        } catch (error) {
            console.error('Error generating quest:', error);
            throw error;
        }
    }
    
    // Generate multiple quests
    async generateQuests(params) {
        try {
            const questParams = { ...params, questCount: params.count || 3 };
            const prompt = createQuestPrompt(questParams);
            const response = await this.generateContent(prompt, GEMINI_MODELS.quest);
            
            if (!response.quests || !Array.isArray(response.quests)) {
                throw new Error('Invalid quests array in AI response');
            }
            
            return response.quests;
        } catch (error) {
            console.error('Error generating quests:', error);
            throw error;
        }
    }
    
    // Generate quiz questions
    async generateQuiz(params) {
        try {
            const prompt = createQuizPrompt(params);
            const response = await this.generateContent(prompt, GEMINI_MODELS.quiz);
            
            if (!response.questions || !Array.isArray(response.questions)) {
                throw new Error('Invalid questions array in AI response');
            }
            
            return response.questions;
        } catch (error) {
            console.error('Error generating quiz:', error);
            throw error;
        }
    }
    
    // Generate single mission
    async generateMission(params) {
        try {
            const prompt = createMissionPrompt(params);
            const response = await this.generateContent(prompt, GEMINI_MODELS.content);
            
            if (!response.mission) {
                throw new Error('No mission found in AI response');
            }
            
            return response.mission;
        } catch (error) {
            console.error('Error generating mission:', error);
            throw error;
        }
    }
    
    // Batch generate content for multiple regions
    async generateRegionalContent(baseParams, states) {
        const results = {};
        
        for (const state of states) {
            try {
                console.log('Generating content for ' + state + '...');
                const stateParams = { ...baseParams, userState: state };
                const quests = await this.generateQuests(stateParams);
                results[state] = { success: true, quests };
                
                await new Promise(resolve => setTimeout(resolve, 2000));
            } catch (error) {
                console.error('Error generating content for ' + state + ':', error);
                results[state] = { success: false, error: error.message };
            }
        }
        
        return results;
    }
    
    // Test API connection
    async testConnection() {
        try {
            const testPrompt = 'Generate a simple JSON response: {"message": "API connection successful", "timestamp": "' + new Date().toISOString() + '"}';
            const response = await this.generateContent(testPrompt);
            return { success: true, response };
        } catch (error) {
            return { success: false, error: error.message };
        }
    }
    
    // Validate API key
    validateApiKey() {
        if (!this.apiKey || this.apiKey === 'YOUR_GEMINI_API_KEY_HERE') {
            throw new Error('Please set your Gemini API key in gemini-config.js');
        }
        return true;
    }
    
    // Get API usage info
    async getApiInfo() {
        try {
            this.validateApiKey();
            return {
                apiKey: this.apiKey.substring(0, 10) + '...',
                apiUrl: this.apiUrl,
                configured: true
            };
        } catch (error) {
            return {
                configured: false,
                error: error.message
            };
        }
    }
}

// Create global instance
export const geminiClient = new GeminiClient();

// Helper function to validate generated content
export function validateGeneratedQuest(quest) {
    const required = ['id', 'title', 'description', 'category', 'difficulty', 'missions'];
    const missing = required.filter(field => !quest[field]);
    
    if (missing.length > 0) {
        throw new Error('Generated quest missing required fields: ' + missing.join(', '));
    }
    
    if (!Array.isArray(quest.missions) || quest.missions.length === 0) {
        throw new Error('Quest must have at least one mission');
    }
    
    quest.missions.forEach((mission, index) => {
        const missionRequired = ['id', 'title', 'description', 'type', 'xpReward', 'content'];
        const missionMissing = missionRequired.filter(field => !mission[field]);
        
        if (missionMissing.length > 0) {
            throw new Error('Mission ' + (index + 1) + ' missing required fields: ' + missionMissing.join(', '));
        }
    });
    
    return true;
}

// Helper function to sanitize AI-generated content
export function sanitizeGeneratedContent(content) {
    if (typeof content === 'string') {
        return content
            .replace(/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi, '')
            .replace(/javascript:/gi, '')
            .replace(/on\w+\s*=/gi, '')
            .trim();
    }
    
    if (typeof content === 'object' && content !== null) {
        const sanitized = {};
        for (const [key, value] of Object.entries(content)) {
            sanitized[key] = sanitizeGeneratedContent(value);
        }
        return sanitized;
    }
    
    return content;
}

// Test function for debugging
export async function testGeminiConnection() {
    try {
        console.log('Testing Gemini API connection...');
        
        const client = new GeminiClient();
        const apiInfo = await client.getApiInfo();
        console.log('API Info:', apiInfo);
        
        if (!apiInfo.configured) {
            throw new Error(apiInfo.error);
        }
        
        const testResult = await client.testConnection();
        console.log('Connection test result:', testResult);
        
        return testResult;
    } catch (error) {
        console.error('Gemini connection test failed:', error);
        return { success: false, error: error.message };
    }
}